---
      - name: Install nginx
        apt: name=nginx state=present

      - name: Copy nginx configuration
        template: src=default.conf dest=/etc/nginx/conf.d/default.conf
        notify: restart nginx

      - name: Remove nginx default vhost
        file: path=/etc/nginx/sites-enabled/default state=absent
        notify: restart nginx

      - name: Setup vhosts
        template: src=vhosts.j2 dest=/etc/nginx/sites-available/{{ item.name }}
        with_items: '{{nginx_vhosts}}'
      
      - name: Enable vhosts
        file: src=/etc/nginx/sites-available/{{ item.name }} dest=/etc/nginx/sites-enabled/{{ item.name }} state=link
        with_items: '{{nginx_vhosts}}'
        notify: reload nginx
