---
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb

#- name: Create Mysql configuration file
#  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
#  notify: 
#  - restart mysql

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  notify:
  - restart mysql

#- name: Ensure correct permissions on mysql directories
#  file:
#    path: "{{ mysql_base_home }}"
#    state: directory
#    owner: mysql
#    group: mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: update mysql root pwd for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost

#- name: Copy the root credentials as .my.cnf file
#  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
#  notify:
#  - restart mysql

#- name: ensure anonymous users are not in the database
#  mysql_user: name='' host={{ item }} state=absent
#  with_items:
#   - localhost
#   - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

#- name: Create the database's
#  mysql_db: name={{ item.name }} state=present
#  with_items: mysql_db
#  when: mysql_db|lower() != 'none'

#- name: Create the database users
#  mysql_user: name={{ item.name }}  password={{ item.pass|default("foobar") }}  
#                priv={{ item.priv|default("*.*:ALL") }} state=present
#  with_items: mysql_users
#  when: mysql_users|lower() != 'none'
